language: node_js
before_script:
- make build
before_deploy:
- make archive
deploy:
  provider: releases
  api_key:
    secure: Zcqb1ezHlakpy+2GfqQgMVoWsLfkSNjG3h/vBQrMYLgfQPuaWBv3TpC46NZeGXcK1d22QeK7XJCfc9A+P9ZNeJRqBRyWS3vbAt2GEktYCBdvyhIPP1v8ZBRcWoXNNi+olsONsHyAX8l2fQuAu7cinDoaqbv8R+8O9DdN00bfvOgXcaAmpUJPGDIDXJeD9ZcZZ/mmVxW461KUcCj5DB2Ep3ebl57As8Hf7BGrdrydc/G1t5rdxBSVw0rv9zc3BA/ngEX86y2d1R2QhGe5xAuCRZNPdwGCb1KKpWD3nHUS61kPPlOQselDV8LOEqWOcgc7sGMyKs/C9m7hLB+k+okKM8PmXGOMw5+FejA6xRwH39eMlpsIC+o4dxEYq9PtqC35qtS9mbwbn419m3rcK59PuQnoZ/93FestzDCio+C4kNp0aUVZS+Q1J/7vNt6wunV/yHkrW3sf5HwYEQ7jARoQhZLIszsss5vVuz7vutdj8eYOZmGn14p9lLTk+HymvIZLS6ZC5LOOhP2Wd39/vAH14EBfNiFij3Wp4bnaJFUCHN15nmZgcpjP5CaPn9o6zwCTyT5ynz7uACMx8ykTxaS65boHcmiLQ+211F4Gvetmd38pgdyICwixHTbXjNsaiN/bMcFDf6Rqg2qDIbCIYGYLnPi15nN5qcOCZ9Art+DQQ6A=
  file: build/SubstringDynamicValue.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: luckymarmot/Paw-SubstringDynamicValue
